export type RootStackParamList = {
  SplashScreen: undefined;
  Login: undefined;
  Register: undefined;
  Home: undefined;
  Profile: undefined;
  MyCourses: undefined;
  CourseLearning: undefined;
  Courses: undefined;
  CourseDetails: { id: string }; 
  Books: undefined;
  BookDetails: { id: string };
  MyWishlist: undefined;
  Cart: undefined;
  BooksCheckout: undefined;
  OverallGrowth: undefined;
  MyTestSeries: undefined;
  TestSeriesDetails: { id: string };
  ViewTest: { id: string }; 
  Blogs: undefined;
  BlogDetails: { id: string }; 
  EditProfile: undefined;
  PaymentHistory: undefined;
  PaymentDetails: undefined;
  JobNotifications: undefined;
  JobDetails: { id: string };
  PreviousPapers: undefined;
  PYQDetails: { examName: string };
  CoinHistory: undefined;
  AllTestSeries: undefined;
  TestSeriesBrowse: undefined;
  TestSeriesHierarchy: { examId?: string; examName?: string; subjectId?: string; subjectName?: string; topicId?: string; topicName?: string } | undefined;
  Syllabus: undefined;
  PublishBlogs: undefined;
  TestInterface: { testId: string };
  TestResults: { testId: string };
  MyPurchasedBooks: undefined;
  PdfViewer: { url: string; title: string }; 
  LiveClasses: undefined;
  ForgotPassword: undefined;
  FreeResources: undefined;
  CurrentAffairs: undefined;
  CurrentAffairsDetails: { id: string };
  SupportTickets: undefined;
  CreateTicket: undefined;
  TicketChat: { id: string; subject: string; ticketId: string };
  ContactSupport: undefined;
  MainDrawer: undefined;
  MainTabs: { screen?: string } | undefined;
  StudentDashboard: undefined;
  StudentMetrics: undefined;
  Leaderboard: undefined;
  Rewards: undefined;
  Notifications: undefined;
  DeviceManagement: undefined;
  Settings: undefined;
  Achievements: undefined;
  MyLearningHub: undefined;
  Error404: undefined;
  Exams: undefined;
  CategoryWiseExams: { categoryId: string; categoryName: string };
  ExamDetails: { slug: string };
  ExamsPage: undefined;
  // --- STUDENT v2 ---
  Coupons: undefined;
  Wallet: undefined;
  PurchaseHistory: undefined;
  ExamsList: undefined;
  ResultsList: undefined;
  ResultDetail: { id: string; attempt?: any };
};
